name: StackOverflow Login #For Fanatic Badge

on:
  schedule:
  - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: docker://guillaumefalourd/ritchiecli:py-3.8
    steps:
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
            && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
            && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
            && cd /tmp \
            && unzip chromedriver_linux64.zip \
            && rm -rf chromedriver_linux64.zip \
            && sudo mv chromedriver /usr/local/bin/chromedriver \
            && sudo chmod +x /usr/local/bin/chromedriver \
            && chromedriver --version
      - name: Ritchie Formula Get Github User (Python) Execution
        env:
            RIT_STACKOVERFLOW_EMAIL: ${{ secrets.RIT_STACKOVERFLOW_EMAIL }}
            RIT_STACKOVERFLOW_PASSWORD: ${{ secrets.RIT_STACKOVERFLOW_PASSWORD }}
            RIT_STACKOVERFLOW_DISPLAY_NAME: ${{ secrets.RIT_STACKOVERFLOW_DISPLAY_NAME }}
            RIT_SENDGRID_API_KEY: ${{ secrets.rit_sendgrid_api_key }}
            RIT_SENDGRID_EMAIL_SENDER: ${{ secrets.rit_sendgrid_email_sender }}            
        run: |
            sudo rit add repo --provider="Github" --name="formulas-python" --repoUrl="https://github.com/GuillaumeFalourd/formulas-python" --priority=1
            sudo rit set credential --provider=stackoverflow --fields=email,password,displayname --values="$RIT_STACKOVERFLOW_EMAIL","$RIT_STACKOVERFLOW_PASSWORD","$RIT_STACKOVERFLOW_DISPLAY_NAME"
            sudo rit set credential --provider=sendgrid --fields=apikey,emailsender --values="$RIT_SENDGRID_API_KEY","$RIT_SENDGRID_EMAIL_SENDER"
            sudo rit stackoverflow login
